### ISSUE TITLE
Problem with websocket reconnect

### ISSUE THREAD

**Issue by michael-82** [aktin/broker#32]
In at least 2 running instances, an error was encountered when the websocket was closed and a reconnection was attempted. The only solution was to restart the aktin client.

May 09, 2023 9:32:09 AM org.aktin.broker.client.live.AbstractExecutionService sendWebsocketPing
INFO: Websocket ping skipped because websocket is closed. Trying reconnect.
May 09, 2023 9:32:09 AM org.aktin.broker.client.live.AbstractExecutionService sendWebsocketPing
WARNING: Websocket ping reconnect failed: Websocket already connected

**Comment by rwm** [comment]
Fixed in v1.5.1
